import { expect, test, type Page, type APIRequestContext } from "@playwright/test";

/**
 * Live scenario suite against the REAL staging server. No stubs.
 *
 * The existing app.spec.ts stubs the API at the network layer, which is right
 * for proving the client renders. It cannot prove the product works: nothing
 * there touches FastAPI, Postgres or the ONNX models. This file does - it logs
 * in, uploads real files, runs real RAG executions and reads the result back.
 *
 * Opt-in by design: it needs a running server and real credentials, so it only
 * registers when HIVEOS_LIVE_BASE is set. The default gate stays hermetic.
 *
 *   HIVEOS_LIVE_BASE=https://hivesystem.ir \
 *   HIVEOS_LIVE_USER=... HIVEOS_LIVE_PASS=... \
 *   npx playwright test live.spec.ts
 */
const BASE = process.env.HIVEOS_LIVE_BASE;
const USER = process.env.HIVEOS_LIVE_USER ?? "";
const PASS = process.env.HIVEOS_LIVE_PASS ?? "";
const ADMIN_USER = process.env.HIVEOS_LIVE_ADMIN_USER ?? "";
const ADMIN_PASS = process.env.HIVEOS_LIVE_ADMIN_PASS ?? "";

test.describe("live staging", () => {
  test.skip(!BASE, "set HIVEOS_LIVE_BASE to run the live suite");

  /**
   * Log in through the real form and land inside the app.
   *
   * The fields are addressed by id, not by label. The label text for the
   * password input ("رمز عبور") also appears in the show-password toggle, so a
   * /گذرواژه|رمز/ label match resolves to two elements and Playwright's strict
   * mode fails the run before it reaches the app - which is a test bug that
   * looks exactly like a broken login.
   */
  async function login(page: Page): Promise<void> {
    await page.goto(`${BASE}/login`);
    await page.locator("#login-username").fill(USER);
    await page.locator("#login-password").fill(PASS);
    await page.getByRole("button", { name: /ورود|ادامه/ }).click();
    // Wait for the URL to LEAVE /login. A path regex such as
    // /\/(chat|knowledge|owner|usage|wallet)?/ cannot do this: the group is
    // optional, so it also matches "/login" and the assertion passes before the
    // session token is stored. Every later step then navigates as an anonymous
    // user and is bounced back to the form, which looks like a broken feature.
    await page.waitForURL((url) => !url.pathname.startsWith("/login"), {
      timeout: 30_000,
    });
  }

  test("boot: login reaches the shell and the shell renders Persian RTL", async ({ page }) => {
    await login(page);
    await expect(page.locator("html")).toHaveAttribute("dir", "rtl");
    await expect(page.getByRole("navigation").first()).toBeVisible();
  });

  // The answer is generated by the real model over the real index and the
  // browser test default is 30 s, which the retrieval + generation path can
  // exceed on this CPU-only host. The inner expect already allows 120 s.
  test("chat: a real RAG answer cites the corpus", async ({ page }) => {
    test.setTimeout(180_000);
    await login(page);
    await page.goto(`${BASE}/chat`);
    // Address the composer by its aria-label. getByRole("textbox").first()
    // picks the conversation-search input in the rail instead, so the question
    // was typed into the wrong field and no execution ever started.
    const box = page.getByLabel("متن پیام");
    await box.fill("بودجه پروژه قناری چقدر است؟");
    await page.getByTestId("send").click();
    // The answer is generated by the real model over the real index; give it room.
    //
    // Assert on the numbers the corpus actually holds rather than on a generic
    // word like "قناری": the citation panel lists source names, so a loose match
    // can pass on the filename without the answer having been generated at all.
    await expect(page.getByText(/۹۸ میلیارد ریال|QNR-7741/).first()).toBeVisible({
      timeout: 120_000,
    });
  });

  test("search: a query absent from the corpus returns nothing, not noise", async ({
    request,
  }) => {
    const token = await apiLogin(request);
    const gib = await request.post(`${BASE}/api/v1/search`, {
      headers: { Authorization: `Bearer ${token}` },
      data: { query: "xyzzy plugh frobnicate qqqqq" },
    });
    expect(gib.ok()).toBeTruthy();
    expect((await gib.json()).data.results).toHaveLength(0); // relevance floor (P2-9)

    const real = await request.post(`${BASE}/api/v1/search`, {
      headers: { Authorization: `Bearer ${token}` },
      data: { query: "بودجه پروژه قناری" },
    });
    expect((await real.json()).data.results.length).toBeGreaterThan(0);
  });

  test("knowledge: every page route loads without a client error", async ({ page }) => {
    const errors: string[] = [];
    page.on("pageerror", (e) => errors.push(e.message));
    await login(page);
    // /agent is no longer a route: the standalone agent page was folded into
    // the chat surface, whose memory panel now owns it (see AppShell). Only the
    // real routes are walked, so this test cannot pass by following a redirect.
    for (const path of ["/chat", "/knowledge", "/usage", "/wallet"]) {
      await page.goto(`${BASE}${path}`);
      await page.waitForLoadState("networkidle");
      await expect(page.locator("body")).not.toContainText("خطای غیرمنتظره");
    }
    expect(errors).toEqual([]);
  });

  test("admin: every workspace loads for a real admin session", async ({ page }) => {
    await page.goto(`${BASE}/admin`);
    await page.locator("#admin-username").fill(ADMIN_USER);
    await page.locator("#admin-password").fill(ADMIN_PASS);
    await page.getByRole("button", { name: /ورود|ادامه/ }).click();
    for (const w of [
      "overview", "organizations", "billing", "operations",
      "ai", "agents", "events", "system",
    ]) {
      await page.goto(`${BASE}/admin/${w === "overview" ? "" : w}`);
      await page.waitForLoadState("networkidle");
      await expect(page.locator("body")).not.toContainText("خطای غیرمنتظره");
    }
  });
});

/** Direct API login, for assertions that do not need the browser. */
async function apiLogin(request: APIRequestContext): Promise<string> {
  const res = await request.post(`${BASE}/api/v1/auth/login`, {
    data: { username: USER, password: PASS },
  });
  expect(res.ok()).toBeTruthy();
  return (await res.json()).data.session.token;
}
