import { expect, test, type Page, type APIRequestContext } from "@playwright/test";

/**
 * Live scenario suite against the REAL staging server. No stubs.
 *
 * The existing app.spec.ts stubs the API at the network layer, which is right
 * for proving the client renders. It cannot prove the product works: nothing
 * there touches FastAPI, Postgres or the ONNX models. This file does - it logs
 * in, uploads real files, runs real RAG executions and reads the result back.
 *
 * Opt-in by design: it needs a running server and real credentials, so it only
 * registers when HIVEOS_LIVE_BASE is set. The default gate stays hermetic.
 *
 *   HIVEOS_LIVE_BASE=https://hivesystem.ir \
 *   HIVEOS_LIVE_USER=... HIVEOS_LIVE_PASS=... \
 *   npx playwright test live.spec.ts
 */
const BASE = process.env.HIVEOS_LIVE_BASE;
const USER = process.env.HIVEOS_LIVE_USER ?? "";
const PASS = process.env.HIVEOS_LIVE_PASS ?? "";
const ADMIN_USER = process.env.HIVEOS_LIVE_ADMIN_USER ?? "";
const ADMIN_PASS = process.env.HIVEOS_LIVE_ADMIN_PASS ?? "";

test.describe("live staging", () => {
  test.skip(!BASE, "set HIVEOS_LIVE_BASE to run the live suite");

  /** Log in through the real form and land inside the app. */
  async function login(page: Page): Promise<void> {
    await page.goto(`${BASE}/login`);
    await page.getByLabel(/نام کاربری|شناسه/).fill(USER);
    await page.getByLabel(/گذرواژه|رمز/).fill(PASS);
    await page.getByRole("button", { name: /ورود|ادامه/ }).click();
    await expect(page).toHaveURL(/\/(chat|knowledge|owner|usage|wallet)?/, { timeout: 30_000 });
  }

  test("boot: login reaches the shell and the shell renders Persian RTL", async ({ page }) => {
    await login(page);
    await expect(page.locator("html")).toHaveAttribute("dir", "rtl");
    await expect(page.getByRole("navigation").first()).toBeVisible();
  });

  test("chat: a real RAG answer cites the corpus", async ({ page }) => {
    await login(page);
    await page.goto(`${BASE}/chat`);
    const box = page.getByRole("textbox").first();
    await box.fill("بودجه پروژه قناری چقدر است؟");
    await box.press("Enter");
    // The answer is generated by the real model over the real index; give it room.
    await expect(page.getByText(/۹۸ میلیارد|قناری|QNR-7741/).first()).toBeVisible({
      timeout: 120_000,
    });
  });

  test("search: a query absent from the corpus returns nothing, not noise", async ({
    request,
  }) => {
    const token = await apiLogin(request);
    const gib = await request.post(`${BASE}/api/v1/search`, {
      headers: { Authorization: `Bearer ${token}` },
      data: { query: "xyzzy plugh frobnicate qqqqq" },
    });
    expect(gib.ok()).toBeTruthy();
    expect((await gib.json()).data.results).toHaveLength(0); // relevance floor (P2-9)

    const real = await request.post(`${BASE}/api/v1/search`, {
      headers: { Authorization: `Bearer ${token}` },
      data: { query: "بودجه پروژه قناری" },
    });
    expect((await real.json()).data.results.length).toBeGreaterThan(0);
  });

  test("knowledge: every page route loads without a client error", async ({ page }) => {
    const errors: string[] = [];
    page.on("pageerror", (e) => errors.push(e.message));
    await login(page);
    for (const path of ["/chat", "/agent", "/knowledge", "/usage", "/wallet"]) {
      await page.goto(`${BASE}${path}`);
      await page.waitForLoadState("networkidle");
      await expect(page.locator("body")).not.toContainText("خطای غیرمنتظره");
    }
    expect(errors).toEqual([]);
  });

  test("admin: every workspace loads for a real admin session", async ({ page }) => {
    await page.goto(`${BASE}/admin`);
    await page.getByLabel(/نام کاربری|شناسه/).fill(ADMIN_USER);
    await page.getByLabel(/گذرواژه|رمز/).fill(ADMIN_PASS);
    await page.getByRole("button", { name: /ورود|ادامه/ }).click();
    for (const w of [
      "overview", "organizations", "billing", "operations",
      "ai", "agents", "events", "system",
    ]) {
      await page.goto(`${BASE}/admin/${w === "overview" ? "" : w}`);
      await page.waitForLoadState("networkidle");
      await expect(page.locator("body")).not.toContainText("خطای غیرمنتظره");
    }
  });
});

/** Direct API login, for assertions that do not need the browser. */
async function apiLogin(request: APIRequestContext): Promise<string> {
  const res = await request.post(`${BASE}/api/v1/auth/login`, {
    data: { username: USER, password: PASS },
  });
  expect(res.ok()).toBeTruthy();
  return (await res.json()).data.session.token;
}
